---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Stop webserver to allow certbot to generate a cert.
  service:
    name: "{{ servicename_webserver }}"
    state: stopped
  when: not letsencrypt_cert.stat.exists
  ignore_errors: yes

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists
  environment:
    USE_PYTHON_3: 1

- name: Start webserver after cert has been generated.
  service:
    name: "{{ servicename_webserver }}"
    state: started
  when: not letsencrypt_cert.stat.exists
  ignore_errors: yes

- name: Restart additional services after cert has been generated.
  service:
    name: "{{ item }}"
    state: restarted
  when: not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_create_additional_services }}"
