---
- name: Search for existing systemd timer for certbot
  ansible.builtin.stat:
    path: "{{ certbot_systemd_timer_file }}"
  register: certbot_systemd_timer_exists

- name: Add cron job for certbot renewal (if configured).
  ansible.builtin.cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  when:
    - not certbot_systemd_timer_exists.stat.exists
